### ISSUE TITLE
global_costmapにObstacleLayerを突っ込むのができなかった問題について

### ISSUE THREAD

**Issue by uhobeike** [uhobeike/raspicat_navigation#78]
メモ
以下のようにObstacleLayerを突っ込んでいたのだが

`global_costmap_params.yaml`
```
plugins:
  - {name: static_layer, type: "costmap_2d::StaticLayer" }
  - {name: obstacles_layer, type: "costmap_2d::ObstacleLayer" }
  - {name: inflation_layer,  type: "costmap_2d::InflationLayer" }
 
```

以下のsensor_frameをlaunch fileに
`<arg name="obstacles_layer/scan/sensor_frame" value="lidar_link"/>`という形で
変更してたら上手くglobal_costmapにObstacleLayerを突っ込むのができなかった

`costmap_common_params.yaml`
```
obstacles_layer:
  enabled: true
  track_unknown_space: false
  trinary_costmap: false
  obstacle_range: 3
  raytrace_range: 3.5
  observation_sources: scan
  scan:
    data_type: LaserScan
    sensor_frame: lidar_link
    topic: /scan
    marking: true
    clearing: true
```
